/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mascotavirtual.memoria;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;

/**
 *
 * @author MarioX27
 */
public class MemoriaFrame extends javax.swing.JFrame {

    /**
     * Creates new form MemoriaFrame
     */
    Memoria tablero = new Memoria();
    public MemoriaFrame() {
        initComponents();
             this.JpMemoria.add( tablero );
        this.JpMemoria.repaint();
        LblMisParejas.setText(Integer.toString(tablero.puntajeMio()));
        LblContra.setText(Integer.toString(tablero.puntajeContra()));
    }
   // actualizar el label
     ActionListener listener = new ActionListener(){
        public void actionPerformed( ActionEvent e ) {
           LblMisParejas.setText( new java.util.Date().toString() );
        }
     };
    public void puntaje(){
      LblMisParejas.setText(Integer.toString(tablero.puntajeMio()));
       LblContra.setText(Integer.toString(tablero.puntajeContra()));
    
    
    }
      
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        JpMemoria = new javax.swing.JPanel();
        BtnSalir = new javax.swing.JButton();
        LblTitulo1 = new javax.swing.JLabel();
        LblTitulo2 = new javax.swing.JLabel();
        LblMisParejas = new javax.swing.JLabel();
        LblContra = new javax.swing.JLabel();
        BtnJugarMemoria = new javax.swing.JButton();
        ChkPuntaje = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                formMouseDragged(evt);
            }
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                formMouseMoved(evt);
            }
        });

        JpMemoria.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        JpMemoria.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                JpMemoriaMouseMoved(evt);
            }
        });
        JpMemoria.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JpMemoriaMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout JpMemoriaLayout = new javax.swing.GroupLayout(JpMemoria);
        JpMemoria.setLayout(JpMemoriaLayout);
        JpMemoriaLayout.setHorizontalGroup(
            JpMemoriaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 748, Short.MAX_VALUE)
        );
        JpMemoriaLayout.setVerticalGroup(
            JpMemoriaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 596, Short.MAX_VALUE)
        );

        BtnSalir.setText("Salir");
        BtnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnSalirActionPerformed(evt);
            }
        });

        LblTitulo1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        LblTitulo1.setText("Parejas:");

        LblTitulo2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        LblTitulo2.setText("Parejas Contra:");

        LblMisParejas.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        LblMisParejas.setText("0");

        LblContra.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        LblContra.setText("0");

        BtnJugarMemoria.setText("Jugar");
        BtnJugarMemoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnJugarMemoriaActionPerformed(evt);
            }
        });

        ChkPuntaje.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ChkPuntajeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(JpMemoria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(LblTitulo1)
                            .addComponent(LblTitulo2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 56, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(LblContra)
                            .addComponent(LblMisParejas))
                        .addGap(46, 46, 46))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ChkPuntaje)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(BtnJugarMemoria, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(BtnSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(38, 38, 38))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(JpMemoria, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(ChkPuntaje)
                .addGap(126, 126, 126)
                .addComponent(BtnJugarMemoria, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addComponent(BtnSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(73, 73, 73)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LblTitulo1)
                    .addComponent(LblMisParejas))
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LblTitulo2)
                    .addComponent(LblContra))
                .addContainerGap(162, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BtnJugarMemoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnJugarMemoriaActionPerformed
        // TODO add your handling code here:
        tablero.inicio();

        LblMisParejas.setText("0");
        LblContra.setText("0");
    }//GEN-LAST:event_BtnJugarMemoriaActionPerformed

    private void BtnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnSalirActionPerformed
        // TODO add your handling code here:
       
    }//GEN-LAST:event_BtnSalirActionPerformed

    private void ChkPuntajeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ChkPuntajeActionPerformed
        // TODO add your handling code here:
         
    }//GEN-LAST:event_ChkPuntajeActionPerformed

    private void JpMemoriaMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JpMemoriaMouseMoved
        // TODO add your handling code here:
    }//GEN-LAST:event_JpMemoriaMouseMoved

    private void JpMemoriaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JpMemoriaMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_JpMemoriaMouseClicked

    private void formMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseMoved
        // TODO add your handling code here:
        
    }//GEN-LAST:event_formMouseMoved

    private void formMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseDragged
        // TODO add your handling code here:
          LblMisParejas.setText(Integer.toString(tablero.puntajeMio()));
        LblContra.setText(Integer.toString(tablero.puntajeContra()));
    }//GEN-LAST:event_formMouseDragged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MemoriaFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MemoriaFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MemoriaFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MemoriaFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MemoriaFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnJugarMemoria;
    private javax.swing.JButton BtnSalir;
    private javax.swing.JCheckBox ChkPuntaje;
    private javax.swing.JPanel JpMemoria;
    private javax.swing.JLabel LblContra;
    private javax.swing.JLabel LblMisParejas;
    private javax.swing.JLabel LblTitulo1;
    private javax.swing.JLabel LblTitulo2;
    // End of variables declaration//GEN-END:variables
}
